# ```Numpy ```

### ```Numpy``` is a third party library for analyzing the data.

In [2]:
import numpy as np # alias means nickname
a=np.array([1,2,3])# 1-d array means elements in a single row
a

array([1, 2, 3])

In [3]:
lst=[1,2,3,4]
arr=np.array(lst) # convert list to array
type(arr),arr

(numpy.ndarray, array([1, 2, 3, 4]))

In [4]:
a=np.arange(1,10)#using range function to print numbers from 1 to 9
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a=np.array([1, 2, 3])
b=np.array([1,2,3])
a+b

array([2, 4, 6])

In [6]:
l=np.ones(1)#1-d array
print(l)
a=np.ones([2,2])#2-d array
print(a)
b=np.zeros(2)
print(b)
c=np.zeros([3,3])
c

[1.]
[[1. 1.]
 [1. 1.]]
[0. 0.]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
a=np.array([[1, 2, 3], [4, 5, 6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [8]:
h=np.linspace(1,10,5) #1 to 10 with 5 equally spaced numbers
h

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [9]:
num=np.arange(1,31).reshape(5,6) # 5 rows and 6 columns means 5x6 matrix here it converts a 1-d array to a 2-d array with specified shape
num

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [10]:
arr1=np.random.random(10)# 10 random floats between 0 and 1
arr1

array([0.75416171, 0.16686048, 0.6351426 , 0.11959129, 0.53064751,
       0.21793672, 0.09553603, 0.77189715, 0.96561355, 0.72506111])

In [26]:
arr=np.arange(1,61).reshape(5,12)
arr
print((arr.shape),(arr.dtype))#data type
arr.size # total number of elements in the array
arr.ndim #dimension of array
arr1=np.linspace(1,10,8).reshape(4,2)
arr1

(5, 12) int64


array([[ 1.        ,  2.28571429],
       [ 3.57142857,  4.85714286],
       [ 6.14285714,  7.42857143],
       [ 8.71428571, 10.        ]])

In [12]:
g=np.arange(1,11).reshape(5,2) # 5 rows and 2 columns
h=g.ravel()
h
g=np.arange(1,11).reshape(5,2).ravel()#converting 2-d into 1-d
g
i=np.arange(1,11).reshape(5,2).flatten() # flattening the array(1-d array)
i

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#transpose of an array
arr=np.arange(1,11).reshape(5,2)
a=arr.T.shape
a


(2, 5)

In [27]:
# indexing and slicing
arr=np.arange(1,11)
print(arr[0])# indexing element
print(arr[1:5])# slicing from index 1 to 4
print(arr[1:11:2])# slicing from index 1 to 4 with step size of 2
arr[3]=10 # changing the value at index 3
print(arr) # modified array after changing the value at index 3

1
[2 3 4 5]
[ 2  4  6  8 10]
[ 1  2  3 10  5  6  7  8  9 10]


In [15]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr[0,2]) # accessing element at row 0, column 2
print(arr[1:3, 0:3]) # slicing rows 1 to 2 and columns 0 to 2
print(arr[0:2, 0:2]) # slicing rows 0 to 1 and columns 0 to 1
print(arr[0:2, 0:2].shape) # shape of the sliced array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
[[4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
(2, 2)


In [16]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1]) # accessing element at row 0, column 1
print(arr.dtype)

2
int64


In [17]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[::-1]) # reversing the array
print(arr[:, ::-1]) # reversing the columns of the array
print(arr[::-1,:]) # reversing the rows of the array

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [18]:
# 3-d array
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
# creating a 3-d array with specific shape
arr=np.arange(40).reshape(2,5,4)# 3-d array with 2 layers, 5 rows, and 4 columns
print(arr.shape) # shape of the 3-d array
print(arr)

(2, 5, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]]


In [20]:
# creating a 3-d array with random integers
arr=np.random.randint(1,10, size=(2,3,4)) # 2 layers, 3 rows, and 4 columns with random integers between 1 and 10
print(arr)
# creating a 3-d array with random floats
arr=np.random.random((2,3,4)) # 2 layers, 3 rows, and 4 columns with random floats between 0 and 1
print(arr)

[[[6 3 2 8]
  [2 1 2 8]
  [7 9 7 1]]

 [[7 3 5 4]
  [2 4 8 1]
  [5 8 9 3]]]
[[[0.97199604 0.5960982  0.51088443 0.34155616]
  [0.93842091 0.25747642 0.94105285 0.5324394 ]
  [0.66715852 0.38474485 0.62253748 0.57636344]]

 [[0.95007236 0.89367711 0.72180914 0.09361558]
  [0.88800621 0.11080571 0.05654526 0.04943541]
  [0.56455106 0.3354065  0.27355093 0.38788458]]]


In [ ]:
# slicing in the 3-d array
arr=np.arange(1,25).reshape(2,3,4) # creating a 3-d array with shape (2, 3, 4)
print(arr)
print(arr[1, 1, 2]) # accessing element at layer 0, row 1, column 2
print(arr[0, 1:4, 1:5]) # slicing all elements in layer 0


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
19
[[ 6  7  8]
 [10 11 12]]


In [22]:
# common operations on arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])  
print(arr1+2)  # adding 2 to each element
print(arr1 * 3)  # multiplying each element by 3
print(arr1 + arr2)  # element-wise addition
print(arr1 - arr2)  # element-wise subtraction
print(arr1 * arr2)  # element-wise multiplication
print(arr1 / arr2)  # element-wise division
print(arr1 ** 2)    # element-wise exponentiation
print(np.mean(arr1))  # mean of the array
print(np.median(arr1))  # median of the array   
print(np.std(arr1))  # standard deviation of the array
print(np.var(arr1))  # variance of the array
arr3=np.array([2,3,5,6,4,8])
arr3.argsort()# returns the indices that would sort the array




[3 4 5]
[3 6 9]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
2.0
2.0
0.816496580927726
0.6666666666666666


array([0, 1, 4, 2, 3, 5])

In [25]:
y=np.linspace(1,10,6).reshape(2,3)
y

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])